branches:
  only:
    - master

install:
  - set QTDIR=C:\Qt\5.12.1\mingw53_32
  - choco install -y InnoSetup
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%;"C:\Program Files (x86)\Inno Setup 5"
build_script:
  - qmake Lidl_Soundboard.pro
  - mingw32-make
after_build:
  - windeployqt release/Lidl_soundboard.exe
  - cmd: cp LICENSE.md release/LICENSE.txt"
  - iscc innosetup.iss
  - rm release/*.o
  - rm release/*.cpp

artifacts:
  - path: Output\Lidl_soundboard-*.exe
  - path: release
    type: zip


