branches:
  only:
    - master
platform:
  - x86

skip_commits:
  files:
    - readme.md
    - .appveyor.yml
    - docs/*

init:
        #- ps: $blockRdp=$true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
install:
        # - choco install -y InnoSetup
  - set QT_VERSION=5.11.3
    #- set PATH=C:\Qt\Tools\mingw730_64\bin;%PATH%;"C:\Program Files (x86)\Inno Setup 5"
  - set PATH=C:\Qt\Tools\mingw530_32\bin;%PATH%;"C:\Program Files (x86)\Inno Setup 5"
  - set PATH=C:\Qt\%QT_VERSION%\bin;C:\Qt\Tools\QtCreator\bin;%PATH%
    #- set PATH=C:\Qt\5.12.1\mingw73_64\bin;C:\Qt\5.12.1\mingw73_64;%PATH%
  - set PATH=C:\Qt\5.11.3\mingw53_32\bin;C:\Qt\5.11.3\mingw53_32;%PATH%

build_script:
  - qmake Lidl_Soundboard.pro
  - mingw32-make
after_build:
  - windeployqt dist/release/Lidl_soundboard.exe
    #  - cmd: cp LICENSE.md release/LICENSE.txt"
    #  - iscc innosetup.iss
  - rm release/*.o
  - rm release/*.cpp
  - rm release/*.h
  - cmd: cp lib/*.dll release/
artifacts:
  - path: Output\Lidl_soundboard-*.exe
  - path: release
    type: zip


