branches:
  only:
    - master

install:
  - choco install -y InnoSetup
  - set PATH=C:\Qt\Tools\mingw730_32\bin;%PATH%;"C:\Program Files (x86)\Inno Setup 5"
  - set PATH=C:\Qt\%QT_VERSION%\bin;C:\Qt\Tools\QtCreator\bin;%PATH%
  - set PATH=C:\Qt\5.12.2\mingw73_32\bin;%PATH%
build_script:
  - qmake Lidl_Soundboard.pro
  - mingw32-make
after_build:
  - windeployqt release/Lidl_soundboard.exe
  - cmd: cp LICENSE.md release/LICENSE.txt"
  - iscc innosetup.iss
  - rm release/*.o
  - rm release/*.cpp

artifacts:
  - path: Output\Lidl_soundboard-*.exe
  - path: release
    type: zip


